### ISSUE TITLE
Edits to ProjectManagement and EthicsGovernance structure and purpose

### ISSUE THREAD

**Issue by rachclark** [HBClab/ProjectTemplateStructure#14]
I would make these changes and push them but I don't quite understand how to do that yet. Anyway, after trying to get Bike, Bike_Atrain, and AMBI into this format, Lauren, Conner, and I have come up with some changes that we think would be more intuitive. 

We would like to propose:

1- StudyBackground  (includes the proposals and bibliography folders)
2- ProjectManagement (includes a Participants folder for tracking sheets, a Recruitment folder for advertisements and emails, and a Visits folder with all the materials and directions and run sheets for each visit...basically all day-to-day handlings for that project)
3- EthicsGovernance (same as before with InformedConsents and a Monitoring folder which would include forms and excel sheets for DSMB (such as eligibility and screening information) and IRB-ContinuingReviews (but this folder would not contain the day-to-day tracking sheet). 
 then 4-Experiments and 5-Dissemination are the same. Otherwise, keep all folders with the same numbers and just add a 5-StudyBackground folder and modify the contents to the first two folders as needed. 

What do you think, James?

**Comment by jdkent** [comment]
> 1- StudyBackground (includes the proposals and bibliography folders)

I interpret this as just a name change for 1-ProjectManagement to 1-StudyBackground. Only Comment is to keep it as ProjectBackground to maintain consistency, unless we define a meaningful/useful difference between Project and Study.

> 2- ProjectManagement (includes a Participants folder for tracking sheets, a Recruitment folder for advertisements and emails, and a Visits folder with all the materials and directions and run sheets for each visit...basically all day-to-day handlings for that project)

I interpret this as moving the monitoring folder from under 2-EthicsGovernance, rename it to 2-ProjectManagement, but maintains it current defined function.

> 3- EthicsGovernance (same as before with InformedConsents and a Monitoring folder which would include forms and excel sheets for DSMB (such as eligibility and screening information) and IRB-ContinuingReviews (but this folder would not contain the day-to-day tracking sheet).

I interpret this to mean the monitoring folder is now for more stable files that will be used for reporting.


I think this looks good, I'll draft up a pull request and you guys can give feedback on if it matches what's proposed here.

P.S.
[This is the lynda tutorial](https://www.lynda.com/Git-tutorials/Git-Essential-Training/100222-2.html) I recommended for Michelle if you want to learn git and how to set up this workflow.
