### ISSUE TITLE
where do behavioral data files belong?

### ISSUE THREAD

**Issue by rachclark** [HBClab/ProjectTemplateStructure#3]
Would they go within the BIDS folder?

**Comment by jdkent** [comment]
Good question, I have the [BIDS formatted behavioral output](https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.cpt8jqa5g0y7) going to the `BIDS/sub-XXX/ses-XXX/beh/` folder

However, I believe that raw data (straight from eprime or psychopy or presentation) should be stored under `BIDS/sourcedata/sub-XXX/ses-XXX/beh`, and if you wanted to check if the behavioral effect is something you want, you can place the csvs/excel files here `BIDS/derivatives/rachclark_beh_pipeline/` and make the group analysis there, just make a README or something to let yourself (and others) know what data you pulled (whether from BIDS or the sourcedata) and some info on what you did.

**Comment by jdkent** [comment]
overlaps with #6 closing this convo and moving it there
