### ISSUE TITLE
create a monitoring folder

### ISSUE THREAD

**Issue by rachclark** [HBClab/ProjectTemplateStructure#5]
Create a Monitoring directory which would include Recruitment information & Tracking sheets. This is where project manager would work out of for tracking and scheduling participants. This would be at the same level of EthicsApproval and ConsentForms within 2-EthicsGovernance.

**Comment by jdkent** [comment]
Please check the pull request #7, to see if that pull request matches what we want.

**Comment by mwvoss** [comment]
pull request #7 looks good to me
